# Generated by Django 4.1.1 on 2022-10-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=100)),
                ('seller_phone', models.CharField(max_length=100)),
                ('seller_raw', models.CharField(max_length=50)),
                ('seller_price', models.CharField(max_length=10)),
            ],
        ),
    ]
