# Generated by Django 4.1.1 on 2022-10-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=50)),
                ('buyer_phone', models.CharField(max_length=50)),
                ('buyer_adhaar', models.CharField(max_length=50)),
                ('buyer_pass1', models.CharField(max_length=50)),
            ],
        ),
    ]
